[package]
name = "orion-exchange"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "~1.0"
serde_derive = "~1.0"
derive-getters = "0.5.0"

[dev-dependencies]
toml = "~0.7"
serde_json = "~1.0"
serde_ini = "0.2.0"
